import Head from 'next/head'
import ChessGame from '../src/components/chess-game'
import {Grid} from '@chakra-ui/react'

export default function Home() {
  return (
    <div>
      <Head>
        <title>React Chess App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Grid
        h='100vh'
        placeContent='center'
        bg='gray.800'
        px={'8'}
      >
        <ChessGame />
      </Grid>
    </div>
  )
}
