import Head from 'next/head'
import ChessBoard from '../src/components/chessboard'
import {Grid} from '@chakra-ui/react'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Grid
        h='100vh'
        placeContent='center'
      >
        <ChessBoard />
      </Grid>
    </div>
  )
}
